matchbook/config/routes.rb
Matchbook::Application.routes.draw do
  get "sessions/new"

  resources :users

  resources :sessions,      :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/users', :to => 'users#show'
  match '/artists', :to => 'artists'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  root :to => 'pages#home'
  

end

matchbook/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  username   :string(255)
#  email      :string(255)
#  birthdate  :date
#  first_name :string(255)
#  last_name  :string(255)
#  zipcode    :integer
#  city       :string(255)
#  state      :string(255)
#  color      :string(255)
#  gender     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :date_joined, :birthdate, :city, :color, :email, :first_name, :gender, :last_name, :state, :username, :zipcode, :password, :password_confirmation
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :username, :presence => true,
                       :length => { :maximum => 50 }
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :confirmation => true,
                       :presence => true,
                       :length => { :within => 6..40 }
                       
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt ==cookie.salt) ? user : nil
  end
  
  private
  
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end
  
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

matchbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

matchbook/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end
  
    def help
    @title = "Help"
  end
  
  def privacy
    @title = "Privacy"
  end
  
end

matchbook/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end
  
  def create
    user = User.authenticate(params[:session][:email], params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "sign in"
      render 'new'
    else
      sign_in user
      redirect_to user
    end
  end
  
  def destroy
  end
end

matchbook/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate,
                :only => [:index, :edit, :update, :destroy,
                          :followers, :following]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  
  def index
    @users = User.paginate(:page => params[:page])
    @title = "All users"
  end
  
  def show
    @user = User.find(params[:id])
#    @microposts = @user.microposts.paginate(:page => params[:page])
    @title = @user.username
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(:page => params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(:page => params[:page])
    render 'show_follow'
  end

  def new
    @user  = User.new
    @title = "Sign up"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to @user, :flash => { :success => "Welcome to the Rock and Roll Matchbook!" }
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  def edit
    @title = "Edit user"
  end
  
  def update
    if @user.update_attributes(params[:user])
      redirect_to @user, :flash => { :success => "Profile updated." }
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, :flash => { :success => "User destroyed." }
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      @user = User.find(params[:id])
      redirect_to(root_path) if !current_user.admin? || current_user?(@user)
    end
end

matchbook/app/helpers/application_helper.rb
module ApplicationHelper

  def title
    base_title = "R&R Matchbook"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  def logo
    image_tag("logo.png", :alt => "Rock and Roll Matchbook", :class => "round")
  end
  
end

matchbook/app/helpers/pages_helper.rb
module PagesHelper
end

matchbook/app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
   cookies.permanent.signed[:remember_token] = [user.id, user.salt]
#   cookies.signed[:remember_token] = [user.id, user.salt]
     self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user
  end
  
  def authenticate
    deny_access unless signed_in?
  end

  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  
  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end
    
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
end

matchbook/app/views/layouts/_footer.html.erb
<footer>
  <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact Us", contact_path %></li>
  </ul>
</footer>

matchbook/app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag("logo.png", :alt => "Rock and Roll Matchbook Logo", :class => "round") %>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li> 
      <% if signed_in? %>
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Help", help_path %></li> 
      <% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign In", signin_path %></li> 
      <% end %>
    </ul>
  </nav>
</header>

matchbook/app/views/layouts/_stylesheets.html.erb
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>

matchbook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
        <%= render 'layouts/header' %>
      <section class="round">
          <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
          <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

matchbook/app/views/pages/about.html.erb
<h1>Rock and Roll Matchbook</h1>
    <p>
      This is the About page for the <a href="http://railstutorial.org/">Rock and Roll Matchbook</a> .
    </p>

matchbook/app/views/pages/contact.html.erb
<h1>Rock and Roll Matchbook</h1>
    <p>
      This is the contact page for the <a href="http://railstutorial.org/">Rock and Roll Matchbook</a> .
    </p>

matchbook/app/views/pages/help.html.erb
This is the Help page.

matchbook/app/views/pages/home.html.erb
<h1>Rock and Roll Matchbook</h1>
    <p>
      This is the home page for the <a href="http://railstutorial.org/">Rock and Roll Matchbook</a> .
    </p>
<%= link_to "Sign up now!", signup_path, :class => "signup_button_round" %>

matchbook/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:
    </h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  
<% end %>

matchbook/app/views/users/_fields.html.erb
<div class="field">
  <%= f.label :username %><br />
  <%= f.text_field :username %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :first_name %><br />
  <%= f.text_field :first_name %>
</div>
<div class="field">
  <%= f.label :last_name %><br />
  <%= f.text_field :last_name %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>

matchbook/app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

matchbook/app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

matchbook/app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>  
<% end %>

matchbook/app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<%= @user.username %>, <%= @user.first_name %> <%= @user.last_name %>, <%= @user.email %><br />
<%=link_to user_path(@user), @user %>